use_default_settings: true

server:
  base_url: http://127.0.0.1:8081
  bind_address: 0.0.0.0
  port: 8080
  secret_key: "CHANGE_ME"
  limiter: true

general:
  instance_name: "SearXNG"
  enable_metrics: false
  debug: false

redis:
  url: redis://redis:6379/0
search:
  formats:
    - html
    - json
