FROM nginx:alpine

COPY index.html /usr/share/nginx/html/
COPY login.html /usr/share/nginx/html/
COPY templates.html /usr/share/nginx/html/
COPY app.js /usr/share/nginx/html/
COPY templates.js /usr/share/nginx/html/
COPY style.css /usr/share/nginx/html/
COPY templates.css /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY index.html /usr/share/nginx/html/
COPY login.html /usr/share/nginx/html/
COPY app.js /usr/share/nginx/html/
COPY style.css /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/conf.d/default.conf
